POST http://localhost:3001/api/links
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2VjMWRlYmE4OTIzYTIzMTFiYWM2MyIsInVzZXJuYW1lIjoianNtaXRoIiwiaWF0IjoxNjkxMzYzODU3LCJleHAiOjE2OTEzNjQ3NTd9.1G_HWsgX5xMrnzaR28aZN7GiHNuObZTZcXVe1oFjSUs

{
    "url": "www.youtube.com",
    "desc": "Youtube",
    "position": 2,
    "user": "64cec1deba8923a2311bac63"
}

###
POST http://localhost:3001/api/links
content-type: application/json 
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJib2IiLCJpZCI6IjY0YzYwYTczMWNlOWVhZjBjZDhkZmZlYiIsImlhdCI6MTY5MDcwMDQ1MSwiZXhwIjoxNjkwNzA0MDUxfQ.2r5MAtimkEm0zDkAr6i0UfH8TwSdWM49jHsD5XIyZek

{
    "url": "www.invalid.com",
    "desc": "Incorrect",
    "position": 0,
    "user": "64c59ae8b888d23d0ed1409e"
}

###
POST http://localhost:3001/api/links
content-type: application/json 
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtaXRoam9obiIsImlkIjoiNjRjNTlhZThiODg4ZDIzZDBlZDE0MDllIiwiaWF0IjoxNjkwNzUzMDYyLCJleHAiOjE2OTA3NTY2NjJ9.M5RlaT13iWiSVpdLL-HkPKJLX9PJlr0Gp7KCRo4C5WU

{
    "url": "www.invalid.com",
    "desc": "Incorrect",
    "position": 0
}
