DELETE http://localhost:3001/api/links/64c60a101ce9eaf0cd8dffe7
content-type: application/json 
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtaXRoam9obiIsImlkIjoiNjRjNTlhZThiODg4ZDIzZDBlZDE0MDllIiwiaWF0IjoxNjkwNzU2NTI3LCJleHAiOjE2OTA3NjAxMjd9.RmXWDyYuUmkvCereKRQdGpJ9KL0jXxV8ptu0l284s40

###
DELETE http://localhost:3001/api/links/64c60a101ce9eaf0cd8dffe0
content-type: application/json 
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtaXRoam9obiIsImlkIjoiNjRjNTlhZThiODg4ZDIzZDBlZDE0MDllIiwiaWF0IjoxNjkwNzU2NTI3LCJleHAiOjE2OTA3NjAxMjd9.RmXWDyYuUmkvCereKRQdGpJ9KL0jXxV8ptu0l284s40