PUT http://localhost:3001/api/users/64cd872340cc2f5a313c56f7
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2Q4NzIzNDBjYzJmNWEzMTNjNTZmNyIsInVzZXJuYW1lIjoianNtaXRoIiwiaWF0IjoxNjkxMTkzNDI0LCJleHAiOjE2OTExOTQzMjR9.d8UpjVVCirUVrv4SeMdXsmfRkZEhZdX051ykptSOGfs

{
    "name": "Neil Smith",
    "username": "johnsmith",
    "email": "johnsmith@gmail.com", 
    "password": "password"
}